### ISSUE TITLE
Enforce "inspire" bibtex tags in full references.

### ISSUE THREAD

**Issue by markscheel** [sxs-collaboration/spectre#1013]
Instead of making up our own bibtex tags in docs/References.bib, we should use tags from https://inspirehep.net.  These tags are apparently collisionless and they are human-readable.

### Component:

- [ ] Code
- [x] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by nilsvu** [comment]
- Shall we just impose the (rather loose) rule "{authors}:{year}{*a-z}" where {authors} is usually the capitalized last named of the first author, but could also be something like "LIGO" (collaboration) or "HesthavenWarburton" (two authors), and {*a-z} means enumerating otherwise ambiguous keys with a, b, c, ...?
- Or do we need to be more precise in imposing a naming scheme?
- Shall we use the exact key from inspirehep.net if one exists?
