### ISSUE TITLE
Remove GOTO action mechanism

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#1036]
# Feature request:

Get rid of it.

### Component:

- [x] Code

**Comment by kidder** [comment]
We will need some way to do conditional jumps, even after we upgrade to phase-dependent action lists.

**Comment by nilsdeppe** [comment]
Closing this because we need some way of dynamically changing the task graph inside of a phase. Even with phase dependent action lists this problem persists. If someone can think of a better method than a goto and label action approach a new issue should be filed.

A concrete example of where we need to change the task graph is the FD subcell limiter. In the case of a troubled cell detection we switch over to a FD scheme, which means we don't use the DG actions anymore but completely different FD actions. Additionally, we will need to "skip" the FD actions for the unlimited cells.

Again, if there's a cleaner way than a goto+label mechanism that would be great, but as it stands we need a method of changing the task graph within a phase (to avoid global syncs).
