### ISSUE TITLE
Update RadiallyFallingFloor

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#1083]
# Feature request:

VariableFixing::RadiallyFallingFloor takes template parameters `Density` and `Pressure` that are no longer needed since we have `db::SimpleTag`, so this should be updated.  Also an open question is whether this fixing should depend upon the equation of state

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by nilsdeppe** [comment]
To summarize a conversation with @carmaza @kidder  and @wthrowe:

- Since we have hydro::Tags now we can just use those instead of the template parameters.
- The current code does not depend on the EoS so, for example, for a polytrope with `Gamma = 4/3` the floor does not not satisfy the relationship `P= K rho^Gamma`.
- Another questionable thing that was discussed was that having the floor go as `r^{-3/2}` means the total mass of the system diverges. @wthrowe and I vaguely recall having a discussion with @ffoucart about this at some point, or at least it being mentioned.

**Comment by ffoucart** [comment]
Regarding the radial dependence of the floors: I am generally skeptical of the $r^{-3/2}$ choice, because of the divergence of the mass, but it is the standard method in the disk community. Most codes use pretty small grids though, and thus the mass of the atmosphere remains small. 
I think that it would be ok to transition to a steeper function once past the disk region, if we want to extend the grid further out. Maybe that's not needed for short-term accretion disk simulations, but it would certainly be useful if the atmosphere extends into the wave zone in binary simulations...

Regarding the EoS dependence, again the standard choice in the disk community is to just have the same floors regardless of the EoS. However, I know that some EoS then trigger the floors more often than others. It's ok for the floor to not satisfy $P=K \rho^\Gamma$ though, as that's just the cold part of the pressure ($T=0$). The floor on the internal energy does not need to correspond to zero-temperature. In fact, I'd recommend to choose a floor corresponding to a strictly positive temperature, to limit the risk of having the code wander into negative-temperature territory.

**Comment by kidder** [comment]
This was fixed in #1102
