### ISSUE TITLE
Missing Parentheses Warning in some CHECK statements

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#110]
In some cases the `CHECK` statements supplied by Catch result in the compiler warning about missing parentheses. The cause if this is that the `CHECK` macro expands to (in v1.9.6 of Catch)

```cpp
try { \
  CATCH_INTERNAL_SUPPRESS_PARENTHESES_WARNINGS \
  ( __catchResult <= expr ).endExpression(); \
  CATCH_INTERNAL_UNSUPPRESS_PARENTHESES_WARNINGS \
} \
```

with

```cpp
#       define CATCH_INTERNAL_SUPPRESS_PARENTHESES_WARNINGS \
            _Pragma( "clang diagnostic push" ) \
            _Pragma( "clang diagnostic ignored \"-Wparentheses\"" )
#       define CATCH_INTERNAL_UNSUPPRESS_PARENTHESES_WARNINGS \
            _Pragma( "clang diagnostic pop" )
```

I have a few questions.

1) Which compiler versions are producing this error?

2) @wthrowe you said there is a missing `pop`. Where did you see this?

Note: We first encountered this with PR #82

**Comment by wthrowe** [comment]
It was changed.  The pop was missing until version 1.8.0, and I was looking at whatever version we were developing against before.  Until two weeks ago that version wasn't supported in this repo either, so I suspect most people haven't updated.  We might want to add a version requirement.

This also means that any knowledge we had about what produced warnings here is obsolete, since it looks like there have been other warning-related changes to catch.  Maybe we should bump our minimum catch version to at least 1.8 and drop the pragmas and see if it still shows up as a problem anywhere.
