### ISSUE TITLE
step_function() gives a compiler error unless static casting DataVector expression

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#1122]
# Bug reports:

### Expected behavior:
~~~~
// Add these lines at line 335 of Test_DataVector.cpp
// These lines work
DataVector debug{{-4.0, 0.0, 4.0}};
DataVector debug_combo = -4.0 * debug + 4.0;
DataVector step = step_function(debug);
DataVector step_combo = step_function(debug_combo);
DataVector step_combo2 = step_function(static_cast<DataVector>(-4.0 * debug + 4.0));

// Expect this line to also work (compile and evaluate correctly)
DataVector step_combo3 = step_function(-4.0 * debug + 4.0);
~~~~
### Current behavior:
~~~~
// This line gives a compiler error: 
// spectre/src/Utilities/PointerVector.hpp:37:24: error: 
// type 'const blaze::SIMDf64FmaddExpr<blaze::SIMDdouble, 
// blaze::SIMDdouble, blaze::SIMDdouble>' does not provide 
// a subscript operator
DataVector step_combo3 = step_function(-4.0 * debug + 4.0);
~~~~
### Environment:

Docker

# Feature request:

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by fmahebert** [comment]
In PointwiseFunctions/AnalyticSolutions/Burgers/Step.cpp I called `step_function` with a different expression as argument and it worked... 

Edit: the call is at line 35 of Step.cpp, and is: `step_function(DataVector - double)`

**Comment by geoffrey4444** [comment]
Thanks, @fmahebert. This fits with my further testing:

~~~~
  // Expect this line to also work (compile and evaluate correctly)
  // DataVector step_combo3 = step_function(-4.0 * debug + 4.0); // breaks

  // Further tests:
  // DataVector step_combo3 = step_function(-4.0 * debug); // breaks
  // DataVector step_combo3 = step_function(-1.0 * debug); // breaks
  // DataVector step_combo3 = step_function(-4.0 + debug); // compiles
  // DataVector step_combo3 = step_function(4.0 * debug); // breaks
~~~~

**Comment by fmahebert** [comment]
Perhaps the problem lies with `*`?

**Comment by moxcodes** [comment]
I'm working on finding a fix for this; the problem seems to be the fact that the blaze internal SIMDf64 is directly accessed via `[] operator` in our custom step_function, where in cascaded expressions that access operator isn't provided to that type (but is to other types).

The two solutions I see to this are:
a) rewrite the internal `step_function` to use only the vector `__mm...` operators as most blaze vector, functions do, rather than having explicit ternary operators and vector accesses
b) remove the `SIMDf64` overload for `step_function` and just let blaze be as fast as it can be when all it has is a function of a double to work with. I think this still works (because the blaze::map looks pretty general), but will almost certainly be slower.
