### ISSUE TITLE
Fluxes are not updated on external boundaries

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#1142]
# Bug reports:

Neither `dg::ComputeNonvonservativeBoundaryFluxes` nor `dg::ImposeDirichletBoundaryConditions` update the `Interface<BoundaryDirectionsInterior, NormalDotFlux<variables_tag>>`. This is a potential source of error. For instance, I don't see where in `EvolveScalarWave` these are updated.

### Expected behavior:

`Interface<BoundaryDirectionsInterior, NormalDotFlux<variables_tag>>` is computed in each step of the algorithm

### Current behavior:

It remains as set in `InitializeElement`.

**Comment by osheamonn** [comment]
So good catch @nilsleiffischer.... I tried evolving a plane wave and errors accumulate as the wave enters the domain pretty rapidly. I didn't catch this when merging BC's since without observers, the only tests I ran were burgers which must've had sufficiently stationary/outflow BC's that this wasn't an issue.
