### ISSUE TITLE
Poisson input file tests fail when run a second time

### ISSUE THREAD

**Issue by fmahebert** [sxs-collaboration/spectre#1256]
### Expected behavior:

Tests run successfully several times in a row

### Current behavior:

The tests `InputFiles.Poisson.Input{1,2,3}D.yaml.execute` fail when run after the first time.

The problem appears to be that these 3 tests create H5 files that are not cleaned up — when run a second time, the tests fail when trying to create these files.

**Comment by nilsvu** [comment]
Indeed the problem is that the H5 files are not cleaned up. The GRMHD test avoids this by simply setting the time between observations larger than the time of the simulation. I'll probably implement a little control into the Poisson observe action to fix this issue in a similar way, but that's not ideal. It would be great to add a testing phase to these input file tests that runs after the simulation has finished. It would test the output and clean up.
