### ISSUE TITLE
Merge OptionTags and Tags namespaces

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#1345]
# Feature request:

We currently have an `OptionTags` namespace that is distinct from `Tags`. I propose to remove it, move its tags into the `Tags` namespace and merge duplicates.

The reason for doing this is that a tag represents a certain quantity or type. It does not matter in which context it is used (DataBox, ConstGlobalCache, initializing a ParallelComponent). Often (or at least occasionally) we want to create a type from options and then store it in the DataBox (e.g. linear solver convergence criteria or logger verbosity). It is inconvenient to have to figure out if the quantity we want to retrieve is represented by a Tag or an OptionTag.

When merging duplicates we have to make sure the interfaces for DataBox and Option tags are perfectly compatible with each other. We could also separate the interfaces, e.g. use `::option_name()` instead of `::name()`.

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by nilsdeppe** [comment]
I like the idea of first making the change for options to go from `::name()` -> `::option_name()`. I think this will be almost necessary since in the DataBox we will want to retrieve things by name at runtime for observing and the length restriction imposed on Options won't help us with unique names. @wthrowe would you be okay with this change?

**Comment by wthrowe** [comment]
I do not think merging the types of tags is a good idea.  Here are a few reasons:

I feel that conceptually they represent very different things.  OptionTags represent program input.  DataBox tags represent program state.  The only cases I see where there is overlap is with component-specific input options where the DataBox is being used as a "local global cache".  In these cases using the same tag for both makes sense, but they are the exception rather than the rule.  (And this use feels vaguely like a hack, although I can't think of anything to replace it with.)

You say that it is currently confusing to know what tag to pull from the DataBox, but if the namespaces are merged then there would be no indication of what tags can be supplied to the option parser, so we seem to have traded one ambiguity for another.

There has been discussion of allowing access to the ConstGlobalCache through the DataBox, and we should consider whether a change like this would prevent that from happening before we implement it, as that seems like a much more useful change to me.  

As for your specific cases, as far as I can tell you only need the convergence criteria in the DataBox because you don't have access to the cache where you need it.  It appears to be constant and global.  Allowing better access to the cache would solve that problem and would also simplify other code.  It is not clear what the future of verbosity is because we don't have a logging design.

So I am opposed to making any changes in this direction until I have seen a good reason for them.  As far as I can tell the only arguments here are that the tag structures look kind of similar and that mixing them is useful in one edge case.  Nothing prevents you from writing specific tags that can function as both where that is useful, but trying to do this in the general case does not make sense to me.

**Comment by nilsvu** [comment]
I agree with your reasoning @wthrowe. Thinking more about this I came to the conclusion that the issue is elsewhere:
- There are indeed different types of tag interfaces, i.e. a struct needs to satisfy different requirements depending on where it is intended to be used: In a DataBox, TaggedTuple, ConstGlobalCache and/or as an Option. These can be (and typically will be) mixed. So this is an example for a struct conforming to multiple _protocols_ in the sense of #1349. The concept of a _Tag_ is the set of structs conforming to one or more of these protocols. So I think enclosing them all in a `Tags` namespace makes sense, or we could decide that the `OptionTag` protocol is sufficiently distinct to have its own namespace (either is fine with me).
- Using `OptionTags` would indeed be greatly improved by allowing to retrieve them out of the ConstGlobalCache through the DataBox. Alternatively we could make the ConstGlobalCache available in compute items (if that’s possible). @nilsdeppe you mentioned you have something working on a branch?

**Comment by kidder** [comment]
From discussions with @nilsdeppe @wthrowe @nilsleiffischer 
We will keep a separate `OptionTags` namespace whose structs are used solely for parsing options from an input file.  I will add a mechanism that makes it easy to get data produced from `OptionTags` into containers such as the `DataBox` or `ConstGlobalCache`
