### ISSUE TITLE
URLs are highlighted as too long

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#1371]
# Bug reports:

### Expected behavior:

When a line (e.g. in the References.bib) is too long and is not a URL, only the non-URL lines should be reported as being too long.

### Current behavior:

All lines, including those with URLs in them are reported if they are too long when there are any lines that don't have URLs and are too long. I.e. a long title will trigger the checks to fail, at which point the long URLs will be printed as problematic.

@hrueter @wthrowe would one of you be able to look into this? My bash and grep skills are not strong enough to do this :)

**Comment by wthrowe** [comment]
The current state was because piping the output through grep to remove the lines would disable the automatic syntax highlighting, but since I gave up and just forced colors on in #1346 it should be safe to just pipe the result of pretty_grep through another grep.  I'll add another commit to #1346 to fix this.

**Comment by nilsdeppe** [comment]
Thank you :D :+1:
