### ISSUE TITLE
Move slice and orientation utils to Domain

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#1440]
# Bug reports:

### Expected behavior:

DataStructures does not depend on Domain because it is considered a lower level (or maybe the lowest level above Utilities and ErrorHandling) library we have.

### Current behavior:

DataStructures depends on Domain because of the slicing and orientation utilities of Variables and Tensors. These utils should be part of Domain rather than part of DataStructures.

**Comment by fmahebert** [comment]
I propose the following changes:
- move Variable slicing utils to `Domain/SliceHelpers.{c,h}pp`
- move Variable orienting utils to `Domain/OrientationMapHelpers.{c,h}pp`.
- move the member function `OrientationMap::permute_from_neighbor(std::array)` to a free function in the new `OrientationMapHelpers`, because it doesn't feel very consistent with the rest of the `OrientationMap` interface.

If I don't hear any objections, I will proceed with this proposal

**Comment by fmahebert** [comment]
On closer examination, the Variable slicing utils currently in `VariablesHelpers.?pp` don't appear to depend on anything from Domain, so the original argument of moving these to fix the dependencies between directories may not apply. The Variable orienting utils do still need to be moved -- but not necessarily the slicing utils.

I think this opens another option to resolve this issue (in addition to the option in my previous comment):
- leave Variable slicing utils in current location, `DataStructures/VariablesHelpers.?pp`
- move Variable orienting utils to `Domain/OrientationMapHelpers.?pp`
- move `OrientationMap::permute_from_neighbor(std::array)` to the new `OrientationMapHelpers`

@nilsdeppe (since you filed the issue but may not have noticed that the slicing utils don't have this dependency), do you still think the slicing utils should be moved?
