### ISSUE TITLE
Interior quantities are used on both sides of the interface when imposing boundary conditions

### ISSUE THREAD

**Issue by osheamonn** [sxs-collaboration/spectre#1447]
I think I've found a potential bug in the initialisation of GRMHD. It seems to not be causing any error in evolutions since any boundary issues that have cropped up have been solved by other means. 

Basically the primitives on the exterior side of the external boundary (the face on which boundary conditions are imposed) are being calculated by slicing the primitives from the volume. The primitives on the interior side of the same face are also being sliced from the volume. This would mean that no boundary condition is being imposed on the exterior primitives, but the boundary condition is being imposed on the exterior conservatives, so they would be inconsistent (on the order of the discontinuity in the conservatives I suppose). 

I think the simplest way around this is to change the primitives from sliced on the boundary to being a simple tag on the boundary. Then when the boundary conditions are being imposed, both primitives and conservatives can be set. Currently the primitives are calculated on the boundary only as a temporary used to calculate the conservatives, they don't get added to the databox. 

# Feature request:

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by nilsdeppe** [comment]
I'm a bit confused. We impose (or at least would like to impose) boundary conditions on the conservative variables by computing the primitives from the analytic solution, then directly computing the primitives. As far as I can remember there's just no need for the primitives on the external boundary in the DataBox.

**Comment by kidder** [comment]
If the BCs are imposed through fluxes, the primitives are needed for computing the flux on the exterior size.  So the question is where does the flux get the primitives from

**Comment by nilsdeppe** [comment]
Okay, so
```cpp
Tags::Interface<Tags::BoundaryDirectionsExterior<VolumeDim>,
                                   typename system::variables_tag>
```
comes from what is set on the boundary. Probably what isn't done properly is that the primitives are recomputed from the conserved variables. This needs further investigation.

**Comment by wthrowe** [comment]
This appears to be worse than we thought.  It turns out that we are actually obtaining the exterior *fluxes* by copying them from the interior.  This sort of works with a simple LLF flux because it will try to pull the conservative variables (which are correct on both sides) together.  For HLL, however, a supersonic inflow results in free boundary conditions, which are obviously unstable in those circumstances.

**Comment by nilsvu** [comment]
For elliptic systems I slice the analytic solution to the exterior boundary and compute fluxes with compute items (not in `develop` yet). Perhaps we can do a similar thing for evolution systems:
```
        ::Tags::Slice<::Tags::BoundaryDirectionsExterior<Dim>,
                      analytic_fields_tag>,
        ::Tags::InterfaceComputeItem<::Tags::BoundaryDirectionsExterior<Dim>,
                                     typename System::compute_analytic_fluxes>,
        ::Tags::InterfaceComputeItem<
            ::Tags::BoundaryDirectionsExterior<Dim>,
            ::Tags::ComputeNormalDotFlux<analytic_fields_tag, Dim,
                                         Frame::Inertial>>,
```

**Comment by wthrowe** [comment]
I will be curious to see what you've done.  It sounds like a good direction to go in, but the evolution fluxes are not currently written in a form that makes this easy.

**Comment by wthrowe** [comment]
Has anyone thought about how to solve this?  This is a fairly serious bug and it has been open for over a year.

Would recomputing the flux in the boundary condition action be sufficient, or is there more required than that?  Is there a way of recomputing the flux that is sufficiently uniform across systems that it can be done in generic code?

**Comment by nilsdeppe** [comment]
I'm addressing this as part of the boundary condition and flux comm changes I'm working on.

I think it's just the recomputation of the flux that's necessary, but as is there's no way of doing so generically because the fluxes can (and do) depend on a bunch of compute tags. The first thing I am doing to the systems is not having the fluxes use a bunch of compute tags and instead compute what they need locally from the evolved (and optionally primitive) variables. I think part of the problem with the current code is that applying boundary conditions isn't really something that is generic. The boundary conditions heavily depend on the system (Dirichlet one could argue for but that's I think it)
