### ISSUE TITLE
Add dense output to RK4

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#1792]
# Bug reports:

### Expected behavior:

Dense output is available. This is just Hermite interpolation and is documented in numerical recipes.

### Current behavior:

No dense output available

**Comment by teukolsky** [comment]
Actually, Hermite interpolation is only 3rd order accurate (using beginning and ending function values and derivatives). Standard RK4 doesn't have a 4th-order dense output without another rhs evaluation. That's one of the reasons 5th-order Dormand-Prince is better (the other is that Dormand-Prince allows adaptive time-stepping.)

**Comment by nilsdeppe** [comment]
The Dormand-Prince stepper only has 4th order accurate dense output without extra function evaluations. From Numerical Recipes: `The Dormand-Prince fifth-order method allows dense output of order four without any further function evaluations.` I think only the continuous extension RK methods actually supply the full order dense output without additional evaluations, but that is because they are specifically designed that way.

**Comment by wthrowe** [comment]
I believe order-`k-1` dense output is sufficient for an order-`k` stepper because the main method loses an order to the local- to global-truncation error change.  (Some methods, like the AB family, use the full order because it is essentially free, but it is not necessary.)

If the coded method is insufficiently accurate, it should be caught by the `TimeStepperTestUtils::check_dense_output` function.

**Comment by geoffrey4444** [comment]
Dense output is merged in  RK4. @wthrowe is investigating whether we need to rethink timestepping accuracy in general, but that’s beyond the scope of this issue
