### ISSUE TITLE
Unit.Evolution.DG.Limiters.HwenoModifiedSolution timeouts

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#2051]
# Bug reports:

### Expected behavior:

Test doesn't time out.

### Current behavior:

When doing `ctest -j4` on my quad core machine I repeatedly get `Unit.Evolution.DG.Limiters.HwenoModifiedSolution` hitting a timeout. Can we reduce the test time somehow or increase the time limit (I don't love the second option if it can be avoided without degrading the test quality)? This test also always times out for me with ASAN on. It might be worth running the test through VTune to see what's taking time

**Comment by fmahebert** [comment]
As part of a larger refactor, this test has been extensively modified and is now named `Unit.Evolution.DG.Limiters.HwenoImpl`.

It is difficult for me to determine if this timeout still occurs, because I hadn't run into it before. @nilsdeppe, would you mind leaving a note on this issue once you've had time to determine if you still see timeouts from the refactored test?

**Comment by nilsdeppe** [comment]
Okay, I'll keep an eye on it over the next few days and update this issue :)

**Comment by nilsdeppe** [comment]
I haven't encountered this in a while, so I think it's fixed
