### ISSUE TITLE
db::tag_is_retrievable is not metaprogramming friendly

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#2144]
```c++
db::tag_is_retrievable<SomeTag, tmpl::_1>
```
does not compile because it looks for `tmpl::_1::tags_list`.  (Similarly with `tmpl::pin<DataBox>`.)  It would be nice if this worked so the function could be passed to brigand things.

**Comment by nilsdeppe** [comment]
Have you tried `tmpl::bind<db::tag_is_retrievable, SomeTag, tmpl::_1>`? Does that work? I'm not sure what you mean with `tmpl::pin<DataBox>`, could you expand on that?

**Comment by wthrowe** [comment]
That works, thank you.  (My vague statement about `tmpl::pin` was because I actually hit this with `tmpl::_1` as the first argument and `tmpl::pin<DataBox>` as the second, which fails because pin doesn't have a tags_list, but I thought the example I gave was simpler.)

**Comment by nilsdeppe** [comment]
Ah okay. I'm glad that worked! To give some insight as to what is happening in Brigand: because `db::tag_is_retrievable` is a type alias it is evaluated immediately (on the `tmpl::_1`).  The `tmpl::bind` delays this evaluation by wrapping the type alias in a struct, which allows brigand to swap in the actually type for `tmpl::_1` before the type alias is evaluated.
