### ISSUE TITLE
Debugging traps should be unconditional

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#2448]
Since #2324, assertion failures cannot be caught in a debugger unless an environment variable is set.  I don't know why this change was made.  There is no discussion of this in the PR, but I think I vaguely remember an in-person discussion about it a long time ago.  All I can recall is suggesting that we not make this change.

**Comment by nilsdeppe** [comment]
The reason this was changed is because of the following discussion with Charm++:

> Nils Deppe  10:25 AM
> Hey folks, is this code intentional?
> ```cpp
>   if(Cmi_truecrash) {
>     printf("CHARM++ FATAL ERROR: %s\n", message);
>     volatile int* ptr = NULL;
>     *ptr = 0; /*Write to null, causing bus error*/
>   } else {
>     charmrun_abort(message);
>     machine_exit(1);
>   }
> ```
> this is in `charm/src/arch/netlrts/machine.C`. A null pointer is dereferenced here, which seems a bit spooky... We get segfaults if building netlrts on macOS and it seems there should be something that prevents us from having that issue. This is Charm 6.10.1
> 
> 10:25
> The build command is: `./build charm++ multicore-darwin-x86_64  -j2 -g -O0`
> 
> Charm Dev  10:29 AM
> Yes, this code is intentional so that assertions trap into the debugger or cause a core dump. Try looking at the backtrace to see what the true cause is
> 
> Nils Deppe  10:31 AM
> We call a abort and then we get a segfault in Charm++ code. That seems undesirable?
> 10:34
> So what's happening is we have tests that check that when we feed in bad input from input files that spectre properly crashes. This is done via a ctest regex check. However, segfaults appear to be deemed bad enough that ctest isn't passing the tests, or the output is not directed correctly. This wasn't an issue in 6.8.x (I'm not saying something is bad or has regressed, just trying to give a bit of a timeline :slightly_smiling_face: )
> 10:34
> This seems to be macOS specific because building netlrts on my machine everything works fine
> 
> Charm Dev  10:37 AM
> For user error like malformed input file, pass a non-zero value to CkExit. Use CkAbort for things that would need to be debugged if encountered.

Basically, Charm++ segfaults when you call `abort` in order to trap for debuggers, but this breaks testing `ASSERT`s with some newer variants of CTest because CTest always fails tests if they segfault. If we call `CkExit` with a non-zero value then the code doesn't segfault so allows us to test assertions, but doesn't trap for debuggers.

I remember there was an in-person discussion that @wthrowe, @kidder, and I had where we discussed this issue. The current solution was suggested since it's analogous to what ASAN does when compiled on clang for GCC (you have to set an env variable to get it to trap in the debugger). I remember us agreeing that this was the least bad solution, but it was a while ago so I wouldn't bet on that :) I know I never loved the solution but I was also unable to come up with a better one that would also safely work in a massively parallel environment. If such a solution exists, I'd be all for going that route, but this is a lower-level than where I know things :)

What I would guess almost certainly needs to happen is that this is documented... :(

**Comment by wthrowe** [comment]
Was there any reason not to do what SpEC does?
```
void Breakpoint() {
  // We send ourselves a SIGTRAP and ignore it.  If we're not being
  // traced, that doesn't do much, but if we are then the tracer can
  // see the signal delivery.  We don't reset the signal handler
  // afterwards in case this is called on multiple threads; we don't
  // want one thread reenabling the default handler just before
  // another calls raise().

  struct sigaction handler;
  handler.sa_handler = sig_ignore;
  handler.sa_flags = 0;
  sigemptyset(&handler.sa_mask);
  sigaction(SIGTRAP, &handler, nullptr);
  raise(SIGTRAP);
}
```

**Comment by nilsdeppe** [comment]
Not that I know of. I did ask the Charm++ folks why they didn't do this and I forgot to follow up with them. I can check what their thoughts are if they know of any reason this could be a problem. Does that sound like a reasonable plan?

**Comment by nilsdeppe** [comment]
Here's what I got back from the lead developer of NAMD (molecular dynamics code that uses charm)


> That seems like the right thing to do. Print message, SIGTRAP, then abort. You still need to distinguish between bugs, for which a stack trace may be useful, and user input or environment errors.

Edit:

I agree that not having the stacktrace would be nice for input file errors, but I think that can be addressed separately later.
