### ISSUE TITLE
DomainHelpers doesn't check for construction of overlapping domains. 

### ISSUE THREAD

**Issue by osheamonn** [sxs-collaboration/spectre#250]
The `set_internal_boundaries` function in DomainHelpers.hpp used to check the rms seperation of the blocks to ensure that a reasonable domain is being constructed.

**Comment by mar-celine** [comment]
I think we decided that `physical_rms_separation` will be added, not as a part of `set_internal_boundaries`, but as part of a separate test for the domain - otherwise `set_internal_boundaries` would need to be templated on the frames as well as take in the coordinate maps as arguments, which are only used for checking the separation.
