### ISSUE TITLE
LibraryVersions.txt does not contain information about library versions

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#2645]
It only contains versions for cmake, python, and the compilers; SpECTRE versioning; some system information; and compiler flags.

```
CMake Version: 3.17.4
SpECTRE Version: 2020.12.7
SpECTRE branch: develop
SpECTRE hash: v2020.12.07
Hostname: ungoliant
Host system: Linux-5.4.60-gentoo
Host system version: 5.4.60-gentoo
Host system processor: x86_64
CMAKE_CXX_FLAGS: -fPIC -fdiagnostics-color=always -ferror-limit=1 -ftemplate-backtrace-limit=0 -march=native
CMAKE_CXX_LINK_FLAGS:  -L/usr/lib64 -fuse-ld=gold
CMAKE_CXX_FLAGS_DEBUG: -g -DSPECTRE_DEBUG
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS: -fPIC -march=native
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: -march=native
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: -march=native -no-pie
CMAKE_BUILD_TYPE: Debug
CMAKE_CXX_COMPILER: /usr/lib/llvm/10/bin/clang++-10
CMAKE_CXX_COMPILER_VERSION: 10.0.1
CMAKE_C_COMPILER: /usr/lib/llvm/10/bin/clang-10
CMAKE_C_COMPILER_VERSION: 10.0.1
CMAKE_Fortran_COMPILER: /usr/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 7.5.0
Python Version: 3.7.9
```

**Comment by fmahebert** [comment]
I think this is because `cmake/SetupVersionFile.cmake`, which is called at the end of our top-level `CMakeLists.txt`, does a write instead of an append. So all the library versions that were written in get overwritten.

**Comment by fmahebert** [comment]
I can easily put in a PR right now that changes the write to an append, and then there will be ~15 lines of library versions at the top of the file.

But is this the correct long-term solution? With this fix, `LibraryVersions.txt` would have ~15 lines of library versions and ~25 lines of other compiler-related information. Seems either this should be split, or the name should better reflect the contents.

**Comment by fmahebert** [comment]
I am working on a PR with some CMake cleanups and I want to address this while I'm at it.

But, as per my previous comment, it is not clear that the simple fix is the correct one, because most of the stuff we are writing (well, trying to write) to LibraryVersions.txt isn't library versions.

Which of the following do we want?
1. LibraryVersions.txt contains just library versions
2. LibraryVersions.txt contains the library versions + "useful info" (this is the closest to what is done now, modulo the WRITE/APPEND bug that erases much of the file content)
3. LibraryVersions.txt contains the entire CMake output

I suggest that if we opt for options 2 or 3, then we should rename LibraryVersions.txt to CMake.log or similar.

**Comment by kidder** [comment]
appears to have been broken by commit 2e87a9d in #2206

**Comment by kidder** [comment]
We need something to overwrite the file whenever cmake is invoked otherwise you get multiple copies of the information.

I am not sure why @nilsdeppe  moved the location of include(SetupVersionFile) in the top level CMakeLists.txt so I don't know whether to:
- move the call back to where it was previously
- split SetupVersionFile.cmake into two parts, one that overwrites the file before any other call appends to the file, and the second to print information that you felt was incorrect unless printed at the end...

**Comment by kidder** [comment]
since I believe LibraryVersions.txt is the file that Formaline uses as input for information it writes into all the output files, it probably makes more sense to have a single file than split it up...

**Comment by kidder** [comment]
so I think we want option 2 of what @fmahebert suggested above
