### ISSUE TITLE
Charmc is not actually invoked

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#2677]
# Bug reports:

In our build system we claim that the linker is replaced by Charm's `charmc` compiler:

https://github.com/sxs-collaboration/spectre/blob/e6d5d2838e5a51687aaffff07ba794cb3910af80/cmake/SetupCharm.cmake#L25

However, this is not the case. The linker is replaced by `WrapLibraryLinker.sh` in `SpectreAddLibraries.cmake`. This leads to issues with linking charm's shared libs on macOS (not sure how it finds the libs on Linux).

**Comment by nilsdeppe** [comment]
Ah interesting, we only needed charmc for the executable link. Ideally I think we get rid of `charmc` and just link everything directly. I think you and I discussed this in another issue. `charmc` does a whole bunch of weird things, especially when you try to pass escaped arguments through it. We never  really wanted to use it for linking but had to because there was no way of getting the link flags out until Charm 6.9 or so.

**Comment by nilsdeppe** [comment]
This was fixed #2680
