### ISSUE TITLE
Some CCE tests segfault with GCC-10 Release builds

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#2718]
# Bug reports:

The following tests segfault:
- Unit.Evolution.Systems.Cce.Equations
- Unit.Evolution.Systems.Cce.InitializeJ
- Unit.Evolution.Systems.Cce.NewmanPenrose

I fixed the BulgedCube code in #2706 by changing some intermediate results in the expression templates. My guess is that this is actually a bug in the GCC-10 optimizer (:cry:) but it could be some weird interaction between Blaze and GCC that is fixed when we move to Blaze 3.9. I would say we wait until we have Blaze 3.9 merged, then test to see if things are magically fixed, if not, then make any necessary code changes.

### Environment:

CI and the container work can be used to reproduce.

**Comment by moxcodes** [comment]
This isn't fixed in the new version of Blaze... I don't have a clear enough handle on what's going on yet to file a Blaze issue (and the specific example from CCE is sufficiently complicated to be ill-suited as an example of the bug).
I've found that at least in the first case I'm looking at, either:
- not using the `SpinWeighted` wrapper for the expression template, or
- omitting the intermediate variable that was included for readability and just putting the entire math operation in a single line

each fixes the problem -- there must be something subtly wrong with assigning the expression templates rather than just continuing to use them in a larger math expression, and it appears to surface only in specific cases.

Either way, I'll have a work-around for the CCE cases soon.
