### ISSUE TITLE
Comparison of vectorized types is broken

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#2978]
This fails:
```c++
const DataVector a{1.0};
const DataVector b{1.0 + 1e-8};
CHECK(a != b);
```
I have verified that the two DataVectors are actually different (so the comparison is the problem, not the construction).  A similar problem affects Variables.  The above passes with 1e-7, so possibly the comparisons are being performed at single precision.

I first noticed this on CI and can reproduce it locally, so it doesn't seem particularly tied to one setup.

**Comment by moxcodes** [comment]
yikes, that's no good... We currently do not define our own comparison operators for our vector types, we inherit from the blaze types. `Variables` similarly performs comparisons directly with the underlying `CustomVector`.
I went over and browsed blaze, and it turns out they have very sneakily defined the equivalence operator as an approximate equivalence:
https://bitbucket.org/blaze-lib/blaze/issues/258/operator-for-blaze-types-is-not-transitive

I suggest the fix of defining our own equivalence operators in `Variables` and `VectorImpl` to use the blaze `equal` function from blaze, which according to the issue _actually_ checks the equality...
(edit: to clarify, I'll be happy to make that fix myself, I just wanted to suggest it here first)

**Comment by wthrowe** [comment]
This is quite a quote (from your link):
> Therefore it is our expectation that most people would assume operator==() to perform an approximate comparison for floating point numbers.

Yes, your proposal sounds right.  Make sure it also works for `DataVector == expression template`.
