### ISSUE TITLE
Behavior of submission scripts is not standardized

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#2987]
The submission scripts for different machines create different directory structures, have different defaults, and possibly other very-user-visible behavior.  They should be standardized to reduce confusion.

**Comment by nilsdeppe** [comment]
Some thoughts on this:
1. I think we should do something similar to SpEC with regard to levs. We should, eventually, standardize what LevN means in terms of target truncation error. We can, before that, do runs as `LevN_%06d`. I don't love SpEC's `_AB`-type naming. While not completely unintuitive, I find just numbers to be a bit easier to deal with. We can do something like 5 digits, which would give us, with a standard 24-hour queue, about 100k days, so almost 3 decades. I doubt we will have any simulations taking that long.
2. I have mixed feelings about the separate Ringdown directory. I think @markscheel said if he could go back he wouldn't have made it separate because it complicates scripts quite a bit. So unless there's an obvious major reason to stick to the `LevN_Ringdown` directory, I say we flatten that out. We've even been discussing just having the C++ executable figure out if it's doing a switch to ringdown. In that case I really see no reason to have a separate sub-directory.
3. I don't really want `LevN_M/Run` directories. This just causes a headache in terms of number of files (we've hit file system limits because of the number of files). I also don't see that it adds anything unless you allow the code to modify input files, which I think we decided strongly against.
4. Do we need a `LevN_M/bin` symlink? I guess this is a way to update the executables in different segments, which we will inevitably need some way to do. @markscheel thoughts on this?
5. While a bit annoying, I think the `EccK/Ev/LevN_M` structure is actually quite reasonable, at least I can't think of anything better.
6. Keeping post-junk initial data in mind, we will need to decide how we want to handle distinguishing the initial data used for different levs (i.e. the stuff we evolved to post-junk) and the output of the elliptic solver. I think SpEC's way of `EvID` and `ID` is confusing here, because people keep associating the output of an elliptic solve as _the_ initial data, which it isn't, it is _some_ initial data. We really want to use relaxed post-junk initial data from the highest levs. We could, for example, have `EccK/Elliptic` then `EccK/EvIdQ/` (`Q` being an integer again to allow for multiple different steps in this process) which holds the highest resolution evolution to the post-junk phase, then have `EccK/Ev/LevN_M` actually start from the end state of `EccK/EvId`, and treat that as `t=0` in the simulation. To me this gives a nice opportunity to insert more steps into the generation of initial conditions, changing `Q` away from `0` as we add more steps.
7. Machine configs: I think it's worth trying @nilsvu's approach with having yaml files that give configuration options to the different systems we use. This is similar to what SpEC does, except SpEC has some giant python or perl file that holds all the options. We can then also read the machine configs from both python and C++ code as needed. We can control things like launch commands, default cores, queues, scratch directories, etc. all from the yaml file. 
8. Job launching from the submit script: I think we probably want something akin to the launcher SpEC has, e.g. a python script that reads the machine config and does the launch, or we can have a python script that takes a default input file and generates the appropriate submit script. #4638 has a huge amount of bash boilerplate code to deal with "am I restarting from a checkpoint or not?", which will be shared across all supercomputers. We should factor this either into a bash or python module, so we don't need to have a copy-paste fest.

**Comment by nilsvu** [comment]
To 6: How about making the output of the initial data solver `Id0` or just `Id`, and subsequent refinements of the initial data `IdQ` (such as ID after junk from highest lev)? Then the initial data solver is just part of the initial data sequence. I also think we shouldn't lock this down too much because we have no idea what we'll come up with in the future in terms of generating initial data, branching evolutions, levs, etc.

To 8: I'm working on this. Happy to take suggestions.

**Comment by nilsdeppe** [comment]
6. I like `IdQ`. Probably best to start numbering immediately. Maybe 2 digits? I doubt we will come up with over 100 different steps in the ID process 😅

**Comment by nilsvu** [comment]
Another note: I think we should try to depend as little as possible on a hardcoded file system structure. Conventions like the one we're outlining here are very useful to organize many runs. But when scripts make too many assumptions about the file system structure they can break very easily, e.g. when relocating files or directories. I think scripts can just take the paths they're operating on as input options, that's usually pretty straightforward with globs and such.

**Comment by markscheel** [comment]
About the separate ringdown directories:   The reason they were done in SpEC is that originally we had no idea how to set the resolution in the ringdown, so each inspiral had 3 ringdowns at different resolutions.    Once we had AMR and we were able to set resolution by a tolerance parameter rather than by explicitly setting numbers of grid points, then the separate ringdown directories were unnecessary.  So I would say get rid of them.

About bin directories:  Yes I think we will want bin directories in every segment.  Hopefully we can make that simpler than in SpEC, where there are bin directories flying all over the place.

**Comment by nilsvu** [comment]
Points 1, 3, 7, 8 are addressed in #4996. Points 2, 5, 6 will be future work on a full BBH procedure (moved to https://github.com/sxs-collaboration/spectre/issues/5021).

To 4. (bin directories): Currently I just copy the executable and submit script templates to the segments directory (not into each individual segment). We could just overwrite it there if we want to update it halfway through the simulation, though of course that means we can't rerun older segments with the old executable. Thoughts?
