### ISSUE TITLE
We should have a python module that can read our output data

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#3414]
Or at least some way to read it without having to reimplement the internals of our h5 representation.

**Comment by nilsvu** [comment]
We do :) Build the Pybindings (https://spectre-code.org/spectre_using_python.html) and use `spectre.IO.H5`

**Comment by wthrowe** [comment]
That still makes me write code that cares about implementation details like observation ids, which I find to be one of the more confusing parts of the whole system.  I was hoping for something where I didn't have to think about the details of how we use H5.

**Comment by nilsvu** [comment]
Yea, a layer on top of the H5 bindings can be useful, though I think it's important that such layers don't obscure too much of the lower-level code. What I mean is, if something is reasonably easy to accomplish with the lower-level code, then a layer of indirection can actually make the code more difficult to learn (you have to learn _another_ interface). I don't like "thin wrappers". Here's some suggestions:

- We can start to build a `spectre.visualization` module that works with our h5 files. In particular, it needs to deal with _multiple_ h5 files, since we write out one per node. We should discuss the design of the module.
- Maybe all you need is a list of _sorted_ observation IDs so you can index them conveniently? Perhaps they should just be sorted by default on the C++ side, by `list_observation_ids`. It's quite simple to accomplish in Python (this is pretty much the same code I posted in Slack, but I thought it's useful to copy it here):

```py
import spectre.IO.H5 as spectre_h5

with spectre_h5.H5File(file_name, 'r') as open_volume_file:
    volume_data = open_volume_file.get_vol('/VolumeData') # Important: leading slash
    sorted_obs_ids = sorted(volume_data.list_observation_ids(), key=volume_data.get_observation_value)
    obs_id = sorted_obs_ids[0] # Easy to index now
    obs_val = element_data.get_observation_value(obs_id)

    # Get tensor data for an element. This can probably be made more convenient, but for max efficiency it's important to expose the contiguous tensor data.
    print(volume_data.list_tensor_components(obs_id))
    field_data = np.asarray(volume_data.get_tensor_component(obs_id, field_name))
    grid_names = volume_data.get_grid_names(obs_id)
    extents = volume_data.get_extents(obs_id)
    grid_name = grid_names[0]
    grid_offset, grid_length = spectre_h5.offset_and_length_for_grid(grid_name, grid_names, extents)
    grid_data = field_data[grid_offset, grid_offset + grid_length]

```

Do you have any suggestions? What use-cases do you have?

**Comment by wthrowe** [comment]
> Yea, a layer on top of the H5 bindings can be useful, though I think it's important that such layers don't obscure too much of the lower-level code. What I mean is, if something is reasonably easy to accomplish with the lower-level code, then a layer of indirection can actually make the code more difficult to learn (you have to learn _another_ interface). I don't like "thin wrappers". Here's some suggestions:

I agree with this, but I think the current module is just such a thin wrapper.  At least the parts I was hitting were objects in 1-1 correspondence with the H5 structures, just with changes like `.get_observation_value(obs_id)` instead of `[obs_id].attrs['observation_value']`.

> 
> * We can start to build a `spectre.visualization` module that works with our h5 files. In particular, it needs to deal with _multiple_ h5 files, since we write out one per node. We should discuss the design of the module.
> * Maybe all you need is a list of _sorted_ observation IDs so you can index them conveniently? 

Why not go object-oriented and return a list of objects representing the data at each time?
```python
     sorted_observations = sorted(volume_data.observations(), key=get_observation_value)
     first_observation = sorted_observations[0]
     obs_val = first_observation.get_observation_value()
```
(I think I have the sort syntax wrong, but you get the idea.)

This might also solve the multiple-files issue you brought up above, since the object can handle collecting the data from all the appropriate places internally.

> Perhaps they should just be sorted by default on the C++ side, by `list_observation_ids`.

Yeah, sorting the list (in either language) before returning it sounds like a good idea.

\<snip>

```python
    volume_data = open_volume_file.get_vol('/VolumeData') # Important: leading slash
```
I also kept hitting that you must leave off the extension.

\<snip>

> Do you have any suggestions? What use-cases do you have?

The use case I hit is that I have a small simulation (~10 observations of Burgers, most recently) and I want to convert the data to TSV for analysis with external programs that can't read H5.  I would like this to be something more like:
```python
volume_data = spectre.IO.H5.open(file_prefix)
data_set = volume_data[subfile]
for observation in data_set:
  for element in observation:
    for x, y in zip(element.coordinates(), element.values()):
      # Handle tensors somehow
      print(observation.observation_value(), x, y)
    print()
```
(When I brought up this problem elsewhere I sorted the coordinates/values, but breaking them up into elements is better.  I just didn't know how to using the current interface.)

**Comment by nilsvu** [comment]
That last snippet you posted would be very nice to get working. However: Do you think we will have enough use cases for it to make it worth building, as opposed to asking people to use the raw H5 files?

If the answer is yes, next question: Build the code in C++ with bindings, or directly in Python? I'm thinking Python, because it's not needed from within a parallel executable. Any parallelism can be done with Python multiprocessing, e.g. to process multiple H5 files in parallel.

Use cases I can think of:

- GenerateXdmf and friends. These need the path into the individual H5 files exposed.
- Scripts like InterpolateVolumeData. For performance it's important to expose the contiguous tensor data.
- Scripts like Render1D. Clear use case, but 1D visualizations are only moderately important.

**Comment by nilsvu** [comment]
Quick note: observation IDs are now sorted by default.

**Comment by nilsvu** [comment]
We have `src/IO/H5/Python/IterElements.py` now. Does that resolve this issue @wthrowe?

**Comment by wthrowe** [comment]
I think so.
