### ISSUE TITLE
How are function-of-time names chosen?

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#3489]
# Bug reports:

I don't understand how the names of functions-of-time are chosen, or what determines them. Input files require I set those names in `TimeDependence` sections -- can I just write any name, and if so, why does the choice exist at all? I looked (briefly) through `DomainCreator.hpp`, `TimeDependence.hpp` and `FunctionOfTime.hpp` but didn't find relevant docs. If they exist, I suggest we refer to them better from these files, and if they don't, I suggest we add some. If the input-file options for these names should remain, I suggest we add instructions for the user how the names should be chosen. In particular, I find help strings like `"FunctionOfTimeName: Names of the functions of time."` very unhelpful.

**Comment by wthrowe** [comment]
I am planning to remove the options, but I haven't investigated yet to see if that causes any issues.

**Comment by nilsdeppe** [comment]
The individual maps need to somehow know the names and the only way I could think of doing it at the time was by specifying them in the domain creator. If this continues to be the case, would it be useful to add to the help string ", if the domain has any time dependence."? I'm not really sure how to clarify that any name is fine as long as they match in the time dependence and wherever else they are used. They really don't exist in a vacuum.

**Comment by nilsvu** [comment]
My confusion is if I need to choose a special name, like write "Translation" to link the FOT to the translation map, of if I can choose whichever name I want. Sounds like it's the latter. If the input-file options need to stay to link FOT across different parts of the program, I suggest adding something like "You can choose any name, as long as it's consistent within this input file". If @wthrowe manages to elide the option altogether, then that would be even better.

**Comment by wthrowe** [comment]
I don't see a reason to allow people to set the names of the control systems in the input file and in most cases the domain options will only make sense with one control system, so that can be hardcoded.

**Comment by nilsdeppe** [comment]
I agree, the reason for the current design is at the time it wasn't clear how much the control system and domain would be tied together. Specifically, having an x, y, and z translation has meant they can't all have the FoT name "Translation". I think this is set up in the `TimeDependences`. Another case where I could see name collisions is if we had `Translation(Rotation(Translation))` where the point we are rotating about is moving. Admittedly, these are rather contrived and likely only needed for testing, but I just want to make sure it's considered :) A case where being able to do weird mesh movement would be nice is testing 3d curved moving mesh DG-FG in Newtonian Euler. The physics is simple but all the other difficult parts could be tested quite thoroughly. Having said all that, I personally never liked having to specify the names in the input file but didn't have enough info about the control system and what types of time dependences we would want to come up with anything better. I think it would also be good to make sure that we can do moving mesh without a control system.

**Comment by wthrowe** [comment]
We can make the control system stuff ignore any functions of time that never expire, which should be enough for analytic movement.

Complicated time-dependences will need specific code in the domain creators anyway, so they can assign names however they like, including from the input file.  Of course, these will have to match control system names if they are not analytic.

**Comment by knelli2** [comment]
The topic of function of time names has come up again now that I'm starting to write the actual control systems and control errors. Discussed with @nilsdeppe, @markscheel and a bit with @wthrowe.
Currently, this is how I was planning on adding control system options:
```
ControlSystems:
  Translation:                <-- Name of function of time *and* control system
    Averager:
    Controller:
    etc...
  Rotation:                   <-- Name of function of time *and* control system
    Averager:
    Controller:
    etc...
```
The "name" of every control system is the name of the function of time that it is controlling. With the current setup, the names of the functions of time in the domain creators would have to match the corresponding control system, meaning that the names could no longer be arbitrary. While this design for control systems isn't definite yet, this is one reason to remove function of time names from domain creator options.

Also, as I was writing some control errors, I found that I needed to access additional functions of time besides the one corresponding to a control system/error (specifically, to compute the translation control error I need the function of time values from expansion and rotation). However, right now there's no easy way to access those names because they could be arbitrarily chosen from options. If the names were hardcoded, then it'd be a lot easier to access them because I wouldn't have to worry about passing names from options and keeping track of them. Another reason to remove them from options.

However, @nilsdeppe raised a good point about "what if we have two of the same map". This kind of breaks what I have done so far. To address that though, I'd say that even though they are the same type of map, they are using different functions of time and thus should have different control systems (if they are being controlled) and thus different names altogether. So if you had some weird domain creator that had two Translation maps, it would be the responsibility of the domain creator to name the functions of time differently based on which control system went with each map.

But this leads to a question of generalization. Do we really want to have to write a new control system for *every* different map we use (that needs to be controlled)? Like for the two Translation map example, I'd hope that I would be able to write a single Translation control system that's general enough to be used for both (i.e. templated on measurements/control errors, if we ever needed that), but I'm not sure.


All this to say that I've been thinking about this a lot but haven't yet decided what I want to do. I'm leaning toward hard coding function of time names, but I need to test some things out to see how that works in practice. Any thoughts/comments are welcome.

**Comment by wthrowe** [comment]
"Hardcoded" here doesn't have to literally mean a constant string, just that it shouldn't depend on input-file contents.  Computed from template parameters or whatever is fine.

A more realistic example than translation maps would be shape control.  The control system there will presumably be templated on something that selects a suffix for the FoT name, and the map might be templated or might just take a normal constructor parameter.

**Comment by nilsvu** [comment]
In the elliptic code I use option groups to identify the various linear solvers. The idea is to have a tiny struct like `RotationControl` defined very far up, possibly all the way up in the metavars or a bit lower where you set up all the different control systems. The struct is used as template parameter to the control system, essentially as a compile-time label. Then it is also passed to option tags and used as an option group for input file options. This could be a way to structure things for you.

**Comment by markscheel** [comment]
Just to make sure that this is written down somewhere,we *will* have two of the same type of map and the same type of control system.  We will have a shape control for AhA and another shape control for AhB, for example.
