### ISSUE TITLE
Change name of  tensor `size()` method to `number_of_independent_components()`

### ISSUE THREAD

**Issue by nikwit** [sxs-collaboration/spectre#3544]
It has happened a few times to me now that I initialized something with `scalar.size()` instead of `get(scalar).size()` which resulted in some hard to debug out of range accessor bugs. 

I would suggest to change this method name to `number_of_independent_components` and perhaps also add a `number_of_grid_points` method. After all, `size` is fairly ambiguous when it comes to Tensors. These are the same names that `Variables` use. How much effort would it be to refactor this?

**Comment by nilsdeppe** [comment]
I would estimate the effort to be enormous. Probably 1 week full time. I don't see this being a reasonable refactor and certainly not the effort. 

Aside from that, calling it "size()" is consistent with the STL naming conventions. I don't see adding a `number_of_grid_points()` method as a good thing since `Tensor` can hold a `double` or pretty much any other type (even modal data). `Variables` are always data on a mesh, so it makes sense to talk about the number of grid points.
