### ISSUE TITLE
Incorrect check on subcell tilde-D in ValenciaDivClean TCI

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#3587]
`src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnDgGrid.cpp`:
```c++
  // require: tilde_d/sqrt{gamma} >= 0.0 (or some positive user-specified value)
  if (min(get(tilde_d) / get(sqrt_det_spatial_metric)) <
          tci_options.minimum_rest_mass_density_times_lorentz_factor or
      min(get(subcell_tilde_d)) <
          tci_options.minimum_rest_mass_density_times_lorentz_factor) {
    return true;
  }
```
Note the lack of a metric factor in the second check.

It is not immediately obvious how to fix this, and I don't think it is causing the prpoblem I am currently debugging, so I'm just filing an issue.

**Comment by nilsdeppe** [comment]
This is intentional. The factor of sqrt{gamma} will be irrelevant in general since it'll be ~1 (deviations would mean we have severe grid stretching).

**Comment by wthrowe** [comment]
It is not O(1) in my runs, because I am, indeed, stretching the grid.

**Comment by wthrowe** [comment]
And, if nothing else, the code contradicts the comment.

**Comment by nilsdeppe** [comment]
Probably the easiest is to just check `tilde{D}` in both cases (and update the comment). If sqrt{gamma} is changing by several orders of magnitude across the domain then this might be problematic because the check would be much more or less stringent depending on where in the domain you are. I'm not sure how much your sqrt{gamma} varies or why it's far from unity so I can't speak to that.

**Comment by wthrowe** [comment]
I'm working in spherical polar, so there's a ~r^2 dependence.  (There's also roughly an overall scaling of the coordinates, but that could be removed by adding some affine maps if necessary.)  I don't have the full range handy, but an unrelated error message I had recently printed a value of ~300 at some unknown point in the domain.

**Comment by nilsdeppe** [comment]
Hmm, okay, I don't expect that to really be a problem since I'd expect for "bad" oscillations that result in unphysical values (negative density) that whether the threshold is 1e-20 or 1e-23 to be unimportant. The only thing I can think of that would cause a problem is if the atmosphere level and the tilde{D} threshold were to overlap. Say if the density in atm is 1e-15 and the tilde{D} is "negative" threshold is 1.0e-16 then it could happen for larger sqrt{gamma} that the atmosphere value of the density causes a tilde{D} that the TCI considers to be negative. I think that's the only constraint/potential issue.

**Comment by wthrowe** [comment]
How about we use the cell average sqrt{gamma} that we can get from the DG grid?  Even a simple average of the values at the colocation points should be good enough to handle an overall scaling of the element.

**Comment by nilsdeppe** [comment]
that should work :) Just to be sure, you're saying use:
```cpp
sum(get(sqrt_det_spatial_metric)) / get(sqrt_det_spatial_metric).size()
```
? (where I'm assuming Blaze has some sort of `sum` function :) )

**Comment by wthrowe** [comment]
Yes, that was my thought.

**Comment by nilsdeppe** [comment]
Okay, that sounds good to me :)
