### ISSUE TITLE
Regridding

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#3937]
We need to interpolate data from one domain to another, e.g. for initial data solved on another domain, or to transition from the inspiral domain to the ringdown domain. I believe this is mostly a matter of iterating over all elements of both domains in some reasonable way. The only unsolved question I have is:

- How do we keep track of the block maps in numerical (initial) data saved to disk?

We could require the domain is specified in the input file, but that may get out of sync when the code is updated. Maybe there's no way around that. Another option would be to store the domain in the H5 files, e.g. serialized with PUP. That also needs the capability to deserialize data that may have been written by an older version of the code (do we have that?). Either way, we need to be very careful and put in lots of checks to make sure the domain hasn't changed in some subtle ways, so the data that's loaded in isn't reinterpreted on a slightly different domain. Checking the inertial coordinates are the same as written in the file might be sufficient.

**Comment by nilsvu** [comment]
@geoffrey4444 @sxs-collaboration/spectre-core-devs some notes for next Thursday

**Comment by nilsdeppe** [comment]
Notes from the call on Thursday, Apr. 28, 2022:

Initial data interpolation:
- Loop over each element on each node then each element requests the
  interpolated data at its grid points. We will not be able to hold the entire
  initial data computational domain on a single node most likely.
- How do you do the interpolation? In particular, we have Block maps in the
  initial data that we somehow need to know.
  ND: Could we do 3d Lagrangian interpolation?
  Saul: Worried about losing accuracy
  Mark: How do we handle in evolution where functions of time, grid frame
        change?
  Need to store Black maps, functions of time, excision spheres. Can we do this
  with PUP? Probably need some sort of versioning?
  How to version in PUP? Answer: serialize an integer version number at the
      beginning of pup function, then during read in need to select accordingly.
  What if Charm++ changes the way they serialize code? Answer: Unlikely to
      change, but not much we can do about it. Ignore for now.
- How to encode the maps into HDF5 files:
  Add a read_write-type function to `CoordinateMap(Base)` that takes a
  `PUP::er` as its argument. Stores an integer for the source frame, target
  frame, dimension, and its a unique integer for the combination of maps it
  holds. This unique integer is stored in a typelist of all the maps that the
  domain creators use. The list would be something like
  ```
  tmpl::list<tmpl::pair<tmpl::list<Affine3D, Wedge<3>>, 0>,
             tmpl::pair<tmpl::list<Shape, Rotation>, 1>,  ...>;
  ```
  These numbers are never allowed to change, new maps can only be added to the
  end of the list incrementing the integer counter, otherwise we will have
  collisions between map types.

  After the four integers corresponding to the frames, dim, and maps is added to
  `PUP::er`, the `pup` functions of all the maps the `CoordinateMap` holds are
  called. These `pup` functions are responsible for their own internal version.
  Note that we cannot `pup` the `CoordinateMap(Base)` since we don't know what
  info Charm++ adds and how that changes over time for base classes.

  We also need to store the FunctionsOfTime (irrelevant for initial data) and
  maybe excision spheres (not clear conclusion reached).

Regridding during the evolution, e.g. for inspiral->ringdown and moving CutX.
- Use the `grid_index` to keep track of which elements belong to which
  domain. When we need to do a regrid we increment the `grid_index` by 1.
- Store a `std::list<Domain>` in the `ConstGlobalCache`. The Domain for each
  element will be retrieved using `domain_list[element_id.grid_index()]`.
- The `std::list<Domain>` can later be changed to some other _pointer stable_
  custom class that accounts for an offset so we don't have to store a lot of
  past Domains, which would all store `YlmSpherepack` objects in their `Shape`
  maps, and would ultimately use a lot of memory.
- Pointer stability is important because we want to append to the
  `std::list<Domain>` when we do a regrid, in order to not have to mutate
  all `ConstGlobalCache` pointers in all `DataBox`es.
- When we want to do a regrid we enter a new phase that figures out what the new
  Domain will be and adds it to all `ConstGlobalCache`s. This will require a
  `const_cast` and so feels a bit unsafe.
  Switch to another phase that inserts all the new DgElementArrays on the new
  Domain (with grid_index() incremented!).
  Switch to another phase that interpolates from the old domain to the new
  domain.
  Switch to another phase that deletes all the old domain DgElementArray
  elements.
  Switch to Evolve phase.
- We also discussed making the `MutableGlobalCache` a nodegroup to avoid the
  `const_cast` but then everything in the `MutableGlobalCache` needs to be
  threadsafe in a lock-free manner. While certainly possible, write lock-free
  code is very difficult and not something we can reasonable expect many people
  to get right.

**Comment by nilsvu** [comment]
Initial data to evolution regridding is done: #4438

Maybe we can get away with starting a new executable for ringdown, which means we don't have to handle multiple domains dynamically. Should we close this issue or open another one for ringdown?

**Comment by nilsvu** [comment]
Closing as done for now, we can open other issues if needed.
