### ISSUE TITLE
Questionable DataBox subitems code

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#3996]
DataBox contains the definition
```c++
using immutable_item_creation_tags =
    tmpl::remove_if<immutable_item_tags, tt::is_a<::Tags::Subitem, tmpl::_1>>;
```
and later uses it as
```c++
// Check that we're not removing a subitem itself, should remove the parent.
using old_immutable_subitem_tags =
    tmpl::filter<typename std::decay_t<Box>::immutable_item_creation_tags,
                 tt::is_a<::Tags::Subitem, tmpl::_1>>;
```
Aside from `tt::is_a` not working in this context, which is addressed by #3995 and doesn't seem to change any behavior, this operation doesn't make sense.  The code is removing all `::Tags::Subitem` types from a list, and then removing everything except `::Tags::Subitem` types, so the resulting list is always empty.

**Comment by kidder** [comment]
yes, that code is nonsense...  I will fix it...

**Comment by kidder** [comment]
- Since  `tt::is_a` did not work as intended, the first type alias `immutable_item_creation_tags` just give back `immutable_item_tags`. 
- Besides being used in the second type alias, `immutable_item_creation_tags` was only used when printing items and pupping items.  
- The second type alias `old_immutable_subitem_tags` is only used in an attempt to trigger a static_assert if you try to remove a subitem of an immutable item.  As currently coded the static_assert is not triggered and the new DataBox would include the parent immutable item and all of its subitems including the one requested to be removed.
- With #3995 the first type alias works, so I have fixed the second type alias and verified that the static_assert is properly triggered.
- I am pretty sure that I had tested this static_assert at some point in my DataBox rewrite, but apparently when factoring those changes into multiple PRs I made an untested change.  
- I should be able to add a static_assert that would have caught the broken `immutable_item_creation_tags`
- It would be nice to be able to test that a static_assert is triggered by bad code.  It looks like it may be possible with cmake/ctest but annoying.
