### ISSUE TITLE
BBH apparent horizon quantities are bogus when observed in inertial frame

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#4132]
# Bug reports:

### Expected behavior:

AH scalar measurements, such as areal mass, should agree regardless of which frame the horizon is observed in.

### Current behavior:

![](https://user-images.githubusercontent.com/867015/180645199-b023375c-042c-4119-88b8-4c163768db5f.png)

The h1p7d curves are the same simulations except the green curve observes the AH in the grid frame.

### Environment:
```
SpECTRE Version: 2022.06.14
Git description: v2021.01.11-1158-g421d3ff6f
Git branch: develop
Git hash: 421d3ff6f60f042b8b3ca6ec68bd8e878db25d55
Hostname: ocean.fullerton.edu
Host system: Linux-3.10.0-957.1.3.el7.x86_64
Host system version: 3.10.0-957.1.3.el7.x86_64
Host system processor: x86_64
Boost version: 1.68.0
Charm++ version: 7.0.0
CHARM_COMPILER: /opt/ohpc/pub/apps/charm_7.0.0_nosmp/bin/charmc
CHARM_SHARED_LIBS: OFF
CHARM_BUILDING_BLOCKS:
CHARM_CC='gcc'
CHARM_CXX='g++'
CHARM_LD='gcc'
CHARM_LDXX='g++'
CHARMBIN='/opt/ohpc/pub/apps/charm_7.0.0_nosmp/bin'
CHARMINC='/opt/ohpc/pub/apps/charm_7.0.0_nosmp/include'
CHARMLIB='/opt/ohpc/pub/apps/charm_7.0.0_nosmp/lib'
CHARMLIBSO=''
CHARM_CC_FLAGS='-DCMK_GFORTRAN -DCMK_GFORTRAN -I/opt/ohpc/pub/apps/charm_7.0.0_nosmp/include -D__CHARMC__=1 -U_FORTIFY_SOURCE -fno-stack-protector -ftls-model=initial-exec'
CHARM_CXX_FLAGS='-DCMK_GFORTRAN -DCMK_GFORTRAN -I/opt/ohpc/pub/apps/charm_7.0.0_nosmp/include -D__CHARMC__=1 -U_FORTIFY_SOURCE -fno-stack-protector -fno-lifetime-dse -ftls-model=initial-exec -std=gnu++11'
CHARM_LD_FLAGS='-ftls-model=initial-exec -rdynamic -L/opt/ohpc/pub/apps/charm_7.0.0_nosmp/lib -lmoduleEveryLB -lckmetis -lck -lmemory-default -lthreads-default -lconverse -lm -lmemory-default -lthreads-default -lldb-rand -lconverse -lckqt -libverbs -lckqt -lz -ldl -lmoduleEveryLB -lmoduleNDMeshStreamer -lmodulecompletion -lz -lm /opt/ohpc/pub/apps/charm_7.0.0_nosmp/lib/conv-static.o'
CHARM_LDXX_FLAGS='-ftls-model=initial-exec -rdynamic -L/opt/ohpc/pub/apps/charm_7.0.0_nosmp/lib -lmoduleEveryLB -lckmetis -lck -lmemory-default -lthreads-default -lconverse -lm -lmemory-default -lthreads-default -lldb-rand -lconverse -lckqt -libverbs -lckqt -lz -ldl -lmoduleEveryLB -lmoduleNDMeshStreamer -lmodulecompletion -lz -lm /opt/ohpc/pub/apps/charm_7.0.0_nosmp/lib/conv-static.o'
BLAS_LIBRARIES: /opt/ohpc/pub/apps/spack/0.12.0/opt/spack/linux-centos7-x86_64/gcc-7.3.0/openblas-0.3.4-tt2coe7yjspglhjqsiyygstq5vkklzye/lib/libopenblas.so
LAPACK_LIBRARIES: /opt/ohpc/pub/apps/spack/0.12.0/opt/spack/linux-centos7-x86_64/gcc-7.3.0/openblas-0.3.4-tt2coe7yjspglhjqsiyygstq5vkklzye/lib/libopenblas.so;-lpthread;-lm;-ldl
LIBXSMM version: 1.16.1
Blaze version: 3.8
GSL version: 2.5
HDF5 version: 1.12.0
jemalloc version: ..
Catch version: 2.11.3
NumPy version: 1.21.1
CMake version: 3.18.5
CMAKE_CXX_FLAGS: 
CMAKE_CXX_LINK_FLAGS: 
CMAKE_CXX_FLAGS_DEBUG: -g -DSPECTRE_DEBUG
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS: 
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: 
CMAKE_BUILD_TYPE: Release
CMAKE_CXX_COMPILER: /opt/ohpc/pub/apps/llvm/10.0.1/bin/clang++
CMAKE_CXX_COMPILER_VERSION: 10.0.1
CMAKE_C_COMPILER: /opt/ohpc/pub/apps/llvm/10.0.1/bin/clang
CMAKE_C_COMPILER_VERSION: 10.0.1
CMAKE_Fortran_COMPILER: /opt/ohpc/pub/compiler/gcc/7.3.0/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 7.3.0
Python version: 3.9.5
```

# Feature request:

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by markscheel** [comment]
Does this behavior depend on the grid resolution?
Does it depend on the AH resolution?
The errors that I see in your plot are less than 1 percent, which might be explainable by insufficient resolution rather than a bug.

(also, I don't understand what all the different curves are in the plot, other than 1 of them is grid frame and the others are inertial frame. What is the difference between all the inertial frame curves?)

**Comment by markscheel** [comment]
The function `strahlkorper_in_different_frame` might be especially sensitive to the AH resolution (i.e. max L). That function is used only when observing in the Inertial frame but finding the horizon in the Grid frame.

**Comment by geoffrey4444** [comment]
@markscheel the behavior does not appear to depend on grid or AH resolution. The differences are different spatial domains (different h refinements, mostly). The only thing that cures the symptom I see is finding AH quantities in the same frame...going up to much higher spatial or AH resolutions makes no difference

**Comment by markscheel** [comment]
The problem is much worse than I thought.

All interpolation in the horizon finder occurs when the horizon is being found.  The metric quantities are interpolated onto the grid-frame Strahlkorper, and these metric quantities are used for finding the horizon, and afterwards they are also used for observing in the grid frame.  The problem is that those same metric quantities (transformed into inertial frame components but *not* re-interpolated) are used for observing in the inertial frame, along with an inertial-frame Strahlkorper that is computed after the grid-frame Strahlkorper is found.  The DataVectors representing the metric quantities have the same number of grid points as the inertial-frame Strahlkorper (so no segfault), but those metric quantities are located on the collocation points of the grid-frame Strahlkorper and not the collocation points of the inertial-frame Strahlkorper.

I think the reason this isn't completely catastrophic (errors are only 1% or so in the above plot) is because the collocation points of the grid-frame Strahlkorper and the inertial-frame Strahlkorper are both on the same correct horizon surface (but at different angles on that surface).  For some maps (like a pure translation or a pure scaling), even the angles should agree and I think everything should (coincidentally) be correct.

There are at least two possible solutions:
* Have an extra round of interpolation after the horizon find is successful. This extra round of interpolation would be like an extra AH-finder iteration, but the target points would be the collocation points of the inertial-frame Strahlkorper.  This means that the AH InterpolationTarget would need an extra internal state, and the callback functions would have an extra layer of complexity as to which Actions they call when.  And `vars_to_interpolate_to_target` would need to become two lists (one for grid frame and one for inertial frame); maybe other things would also need to be split into two parts.
* Do what SpEC does:  Only two Observers in SpEC use information from the Inertial-frame Strahlkorper: trajectory and spin-direction.  All other observers in SpEC output scalars that can be computed in any frame, and in SpEC they are always computed in the frame where the AH is found.  And the trajectory and spin-direction observers in SpEC don't use metric data on the Inertial-frame Strahlkorper.  This seems like a simpler solution to me, and it would also be more efficient because there is less interpolation.

**Comment by markscheel** [comment]
SpECTRE meeting Aug 8 2022: Lets go with the 2nd solution: observe everything in grid frame that can be observed in grid frame, like SpEC does.
This means:
  * Spin-direction observer needs to be rewritten to take both Grid-frame and Inertial-frame Strahlkorpers.
  * `vars_to_interpolate_to_target` will get smaller.
  * Trajectory observer (if we want one, independent of the control system output), will be easy.
