### ISSUE TITLE
Determine if charm++ load balancing works for BBH

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#4581]
Does charm++ load balancing work for BBH evolutions? I.e., does it improve performance without breaking things (like causing the code to sometimes crash)?

**Comment by knelli2** [comment]
I've looked into this. The answer is no but sort of yes.

Sort of yes, because when LB actually does work, I get a factor of 1.5x speedup. Which is good.

No, because after a load balance, sometimes the run deadlocks, sometimes it doesn't. It's seemingly random on when it deadlocks vs when it continues because I've run on the exact same nodes on Wheeler and both scenarios has occured. It's unclear why this is happening, so I'd have to dig quite a bit deeper to figure out why this isn't working.

**Comment by nilsdeppe** [comment]
We are not going to push Charm++ LB at this time. We can revisit this later.
