### ISSUE TITLE
Error tests pass with no regex

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#546]
As seen in #539, error tests pass under some setups if the OutputRegex is missing or malformed.

**Comment by nilsdeppe** [comment]
There are 2 (or more) related issues:

- The missing `]` at the end of the OutputRegex as in #539 
- Why do the tests pass with no OutputRegex?

**Comment by kidder** [comment]
The issue was that `cmake/SpectreAddCatchTests.cmake` only marks the test as a failure test if `cmake/SpectreParseTests.py` successfully finds a non-empty OutputRegex string.  If the attribute is missing or not found between `[[` and `]]`, then `SpectreParseTests.py` wrote an empty string for the OutputRegex.
