### ISSUE TITLE
Commented code in tests/Unit/Evolution/Particles/MonteCarlo/Test_Scattering.cpp

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#5926]
`tests/Unit/Evolution/Particles/MonteCarlo/Test_Scattering.cpp` has about 150 lines of commented-out code.  This needs to be removed or uncommented, as in it's current state it won't be maintained.

**Comment by ffoucart** [comment]
We talked a fair amount about this with @nilsdeppe and @kidder during code review. The issue is that this is an important piece of code to test that the diffusion method does what it's supposed to do, and so we want to have it on record; but it's too costly to run as a test regularly. I'm open to other ways to have it in the code, but so far this is the only method that didn't lead to some sort of failure of the tests due to unused code.

**Comment by wthrowe** [comment]
I uncommented it in #5928 so that it is compiled.
