### ISSUE TITLE
Set BBH evolution parameters from initial data

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#5952]
To robustly start an inspiral from initial data many parameters have to be set, such as control system timescales. We have to look at how SpEC computes these parameters from the initial data and do something similar in `support/Pipelines/Bbh/Inspiral.py`.

**Comment by knelli2** [comment]
This is likely going to be adapted from DoMultipleRuns in SpEC

**Comment by nilsdeppe** [comment]
One thing to note is that SpEC chooses many parameters based on the initial data grid. However, for high spins and large mass ratios this causes problems because slightly suboptimal choices for these cases result in evolution failures. We should choose the parameters based on the evolution grid we are using. The particularly problematic case has been the size map time derivatives. Likely we should evolve a couple time steps with an RK stepper (avoid self start), measure the AH movement, and then initialize the time steps using that. We might even have to iterate a few times.

**Comment by knelli2** [comment]
I agree, this sounds like something we'll need to address, especially once we start trying to simulate more extreme systems. I think a stepping stone to this is to first initialize the shape and size maps with some kind of information from the ID solve, because at present the shape and size coefs are just chosen to be 0. I'll have to coordinate with @nilsvu to see how to do that

**Comment by nilsdeppe** [comment]
Sounds good! I agree, first step is to essentially match SpEC!

**Comment by knelli2** [comment]
Done in #5957
