### ISSUE TITLE
Questions/comments on CCE tutorial

### ISSUE THREAD

**Issue by moble** [sxs-collaboration/spectre#6053]
I've gone through the CCE tutorial, and it looks pretty good.  I think it should be very helpful to users in the workshop.  I have a few fairly minor comments and questions about it, though.

* Under "Acquiring the CCE module", it says that there should be a tarball in every release starting from late May 2024.  I guess that release doesn't exist yet, but when it does, I assume it will be in the "Assets" section.  If so, that should probably be mentioned, because there can be a lot of text to look through, especially for people who haven't looked at a release for the assets before.
* I'm not convinced that the HDF5 type for the "Legend" attribute is very important, and it kind of hits like this tutorial is going to be more of a slog than it really is.
* I think the iterative angular solve warning I got was at least a couple orders of magnitude larger than the 2e-8 in the example.  Is there some level at which I should be worried that the result is just garbage?
* Going from the `ExampleInput.yaml` that @nilsdeppe pointed me to, my output seemed to have excessively fine time steps.  This was also something I saw in data that Nils had run himself.  Throughout inspiral the timestep is ~4e-2, and drops as low as ~5e-3 after merger; compare these to 0.5 and 0.05, respectively, for a typical extrapolated waveform.  It really makes BMS correction extraordinarily slow.  The tutorial suggests `ScriOutputDensity` is important, but that's already just 1.  Is there some other default we could tweak to lighten the load a bit?
* It looks like the datasets in the CCE output always include ell=0 and ell=1 modes, even when the spin is nonzero.  This may be surprising (it was to me), so I think it should be mentioned in the "Output from CCE" section, right under where the h5ls output is listed.  And maybe remind the reader that there's a "Legend" attribute that's relevant.
* In the BMS-correction code in `scri`, there's an option to correct by the Christodoulou mass.  Where is this number found?
* The link to the `scri` tutorial should probably point directly to [the relevant section](https://scri.readthedocs.io/en/latest/tutorial_abd.html#loading-cce-data-and-adjusting-the-bms-frame), because there's a lot on that page, and it's not clear where to find the part about adjust the BMS frame.

**Comment by nilsdeppe** [comment]
Thanks, Mike!
1. Legend attribute: it turns out this was an issue! Deborah had the encoding incorrect or something like that and everything exploded in a cryptic manner. Do you have a suggestion on how to make sure this is clear but maybe not intrusive?
2. Output density: So this is a slightly bigger improvement that needs to be looked at. @keefemitman suggested limiting the time step size to 0.1M. However, CCE currently doesn't have an option to output every N steps, only N times per step. Presumably what's happening is you're getting output at 0.1M density and this is just way too often? What I want to do but haven't had time yet is to make it so we can output data every N steps in addition to N times per step. I'll check to see how difficult that is to add.

**Comment by keefemitman** [comment]
@moble the very fine time steps stem from the error based time stepping that CCE utilizes; this is why I added the `t_interpolate` option (https://github.com/moble/scri/blob/62df4db6099bd3d11035e2a6325d2524e6281168/scri/SpEC/file_io/__init__.py#L485) to `create_abd_from_h5` because, for practical purposes, we will always want to use the time array of the worldtube from the Cauchy evolution as `t_interpolate`. (At least this is what we decided on a while back in the vacuum call for the catalog).

**Comment by knelli2** [comment]
Thanks for going through this @moble! I can definitely implement these suggestions. Yeah I think unfortunately the legend stuff is important since our H5 IO looks for it. I also think @keefemitman's solution for the time stepping is the way to go, and we can address outputting every N steps in the future.
