### ISSUE TITLE
Git hooks can go wrong after some git operations.

### ISSUE THREAD

**Issue by fmahebert** [sxs-collaboration/spectre#63]
This ticket is to document an issue I encountered, but am not sure how to reproduce:

**Bad git operations can leave the git hooks in a state that prevents normal work in the repository**

Here's what I know:

I (somehow) messed up an interactive rebase, and attempted to reset to a pre-rebase state with `git reset --hard HEAD@{N}`. The tracked files were restored as expected.

However, I was then unable to run most git commands (e.g. `git commit --amend`) due to two files triggering the pre-commit hook for having lines over 80 chars. These files are:
```
build/CMakeFiles/3.8.0/CompilerIdCxx/CmakeCXXCompilerId.cpp
tests/Unit/Numerical/Spectral/Test_DefiniteIntegral.cpp
```
It is true that both of these files have lines over 80 chars (*). But as I had no local changes to these files, I would not expect the git hooks to prevent me from committing other changes. Ultimately I resolved the problem by `rm -r .git/hooks`. I suspect a cached file in this directory ended up in a bad state during the broken rebase/reset process.

If anyone else encounters this problem, please comment with any further information!

---

(*) The CMake file is not tracked by the repo, but the test is. This brings up two secondary issues:
1. The git hook should probably not trigger on a CMake-generated file.
2. How did our test get past the 80-char git hooks??

**Comment by fmahebert** [comment]
After repeatedly encountering this "overzealous" git hook even with no fancy git operations, I have found a way of reproducing it using only simple commands:

```
git clone https://github.com/sxs-collaboration/spectre spectre-test-hooks
cd spectre-test-hooks
(optional) git commit --amend --no-edit # works: updates hash but does not change any files
mkdir build && cd build
cmake -D CHARM_ROOT=<blah> ..
cd ..
git commit --amend --no-edit # fails: finds lines over 80 chars
```

Here is the failure message:
```
Found lines over 80 characters:
./build/CMakeFiles/3.8.0/CompilerIdCXX/CMakeCXXCompilerId.cpp:215:#elif defined(__VISUALDSPVERSION__) || defined(__ADSPBLACKFIN__) || defined(__ADSPTS__) || defined(__ADSP21000__)
./build/CMakeFiles/3.8.0/CompilerIdCXX/CMakeCXXCompilerId.cpp:318:#elif defined(_AIX) || defined(__AIX) || defined(__AIX__) || defined(__aix) || defined(__aix__)
./build/Informer/InfoFromBuild.cpp:33:    os << "Compiled in directory:        /home/francois/code/spectre-test-hooks/build\n";
./build/Informer/InfoFromBuild.cpp:34:    os << "Source directory is:          /home/francois/code/spectre-test-hooks\n";
./tests/Unit/Numerical/Spectral/Test_DefiniteIntegral.cpp:45:        integrand.get()[index_it.offset()] = pow(x[index_it()[0]], a) * pow(y[index_it()[1]], b);
./tests/Unit/Numerical/Spectral/Test_DefiniteIntegral.cpp:100:  for (size_t n0 = min_extents; n0 <= std::min(6_st, Basis::lgl::maximum_number_of_pts); ++n0) {
./tests/Unit/Numerical/Spectral/Test_DefiniteIntegral.cpp:101:    for (size_t n1 = min_extents; n1 <= std::min(7_st, Basis::lgl::maximum_number_of_pts); ++n1) {
./tests/Unit/Numerical/Spectral/Test_DefiniteIntegral.cpp:102:      for (size_t n2 = min_extents; n2 <= std::min(8_st, Basis::lgl::maximum_number_of_pts); ++n2) {
./src/Numerical/RootFinding/RootFinder.hpp:38:  auto result = boost::math::tools::toms748_solve(f, lower_bound-absolute_tolerance, upper_bound+absolute_tolerance,
```

**Comment by fmahebert** [comment]
I can open a new issue if we prefer, as the original title/post do not correctly identify the problem.

**Comment by nilsdeppe** [comment]
I think this issue is fine (I can edit the title you want me to change it).

With the given example (I'm going to reformat the bad files in `tests` and `src`) I think it's more of an expectation issue. You are trying to create a commit with no files edited and so git (for some reason that I don't yet understand) determines `git diff --cached` during the pre-commit phase to be all files in your source directory, which in your case also includes the build directory. Since I generally don't make empty commits this explains why I haven't come across this. Maybe @wthrowe has some idea about what the technically correct behavior here should be. I.e. is the current behavior what one should expect, or is there a way detect this sort of commit and bail out on the git hooks passing them happily?

**Comment by wthrowe** [comment]
The culprit is the command `find $commit_files -name '*.[ch]pp'` on line 37 of the hook.  find with no paths defaults to `.`.  This presumably also triggers in a commit that only deletes files or just changes modes.

We should probably just skip all the checks if the list is empty.  This would also allow the special-casing for an empty list later in the script to be removed.

**Comment by fmahebert** [comment]
I recognize that my previous example seems a little contrived, for the sake of being minimal.

I claim that the general idea is reasonable in a workflow where I use interactive rebases to reword some commit messages, perhaps to fix typoes, to remove "WIP" notes, and so on.

Here's an example to illustrate:
```
git clone https://github.com/sxs-collaboration/spectre spectre-test-hooks
cd spectre-test-hooks
touch dummy_file_a
git add dummy_file_a && commit -m "Add dummy_file_a" # (*)
touch dummy_file_b
git add dummy_file_b && commit -m "Add dummy_file_b"  # (*)
(optional) git rebase -i origin/develop # can reword commits
mkdir build && cd build
cmake -D CHARM_ROOT=<blah> ..
cd ..
git rebase -i origin/develop # cannot reword commits: fails due to lines over 80 chars
```

(*) Note that this example confirms an additional secondary bug: the commit hooks seem not to activate until after cmake is run. In this case, my dummy files have no license header, and therefore should not pass the commit hooks. If I reorder this example so I run cmake before touching and adding the dummy files, then the "license" git hook triggers and prevents the commit.

---

To summarize, then:
1. The commit hooks are applied to every file when the `git diff` is empty. I believe @wthrowe's comment addresses this.
2. The commit hooks are not checked until *after* cmake is run.
3. Some files are getting committed with long lines in spite of the commit hooks. Conceivably this is due to (2) above, or due to commit ordering (long lines committed before hooks introduced).

**Comment by nilsdeppe** [comment]
1) Yes, we should be calling `exit 0` if the file list is empty. I tested your rebase example and that is resolved then
2) You cannot add the hooks in any other way. For good reason Git doesn't allow arbitrary code execution just from cloning a reposity
3) This occurred before the git hooks were in place. However, this does highlight that we should have an additional check in place. How about having a Travis build check the line length, tabulations, etc.? The license header would take a bit more work since we include some CMake files that are from other projects, but we could probably then just skip the CMake directory. I really hope nobody commits CMake files without running CMake first... Then again, if it's possible, someone will do it so maybe we should have a list of files that are expected to not have a license header and exclude those. This would mean the list needs to be updated if someone adds another  external file, but that should be rare.

**Comment by fmahebert** [comment]
1. ✅
2. Okay, I agree this is the sensible thing for Git to do.
3. A few thoughts:
  * Can Travis examine only the files which changed in a set of "new" commits? My understanding was that this is hard. It may not make sense to check every file every time.
  * Since the CMake build generates `.cpp` files with lines over 80 chars, these files would have to be excluded as well. Or perhaps create a `build` dir that is not inside the repo.
  * If the number of excluded files is small, and changes rarely, I think it is okay to have an explicit list. But what if we end up bundling other external files, perhaps code? This approach could become cumbersome.
