### ISSUE TITLE
Documentation improvements on corner ordering scheme.

### ISSUE THREAD

**Issue by markscheel** [sxs-collaboration/spectre#725]
# Bug reports:

In tutorial_orientations.html, it is unclear in the Local Corner Numbering Scheme discussion
what the coordinates xi, eta, and zeta are. Are they x,y,z or are they z,y,x?
I am guessing x,y,z by the order in which they are given, but the compact format (000,001, etc) lists them in the opposite order so I am not sure.

# Feature request:

### Component:

- [ ] Code
- [x] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by kidder** [comment]
Can you be more specific about what you find confusing?  I agree that this tutorial can use some improvement because it mixes information about how one would specify a new domain creator and implementation details of how the corners are used to deduce neighbors and their relative orientation.

(xi,eta,zeta) are the logical coordinates of each block and have nothing to do with (x,y,z).  

What you call the compact format is an implementation detail that shows how a local corner number in binary is related to lower/upper logical directions in which case the lowest dimension is the right-most binary digit (this makes it easier for the implementation to handle arbitrary dimensions).

Also it would be useful to know why you were reading the tutorial, as this tutorial could use a better introduction.

**Comment by markscheel** [comment]
I think you have answered my question in your comment: I wanted to know if xi is the lowest dimension or if zeta is the lowest dimension; apparently xi is the lowest dimension and zeta is the highest dimension.   Or in other words, I wanted to know the ordering of the logical coordinates.  (We have a convention for "x,y,z" that x is chosen to be the lowest dimension, but it wasn't clear to me what the ordering of xi,eta,zeta was).

The reason I was reading the tutorial:  I am trying to construct a test Domain that is made up of several Blocks, like the `corners_for_a_3d_cube` example in Test_DomainHelpers.cpp.  But it is not obvious to me how to set up the CoordinateMaps for this case because it's not obvious to me how the eight blocks are arranged with respect to each other.

**Comment by mar-celine** [comment]
Hi Mark, you can look at the function `maps_for_rectilinear_domains` in DomainHelpers, as well as the test MapsForRectilinearDomains  - what you want should look something like this:

  `const std::vector<
      std::unique_ptr<CoordinateMapBase<Frame::Logical, Frame::Inertial, 3>>>
      affine_maps_3d = maps_for_rectilinear_domains<Frame::Inertial>(
          Index<3>{2, 2, 2},
          std::array<std::vector<double>, 3>{
              {{0.0, 0.5, 2.0}, {0.0, 1.0, 2.0}, {-0.4, 0.3, 1.0}}},
          {Index<3>{}}, false);`

The blocks in this domain make up a 2x2x2 rubik's cube shape, and are ordered from the lowest corner to the highest corner as follows:
1st cube: lower end in x,y,z
2nd cube: upper end in x, lower end in y and z,
3rd cube: lower end in x, upper end in y and z,
4th cube, upper end in x and y, lower end in z, and so on

I am working on improving the tutorial at the moment so I appreciate your feedback!

**Comment by kidder** [comment]
@markscheel did #738 address this issue or is there anything else you want?

**Comment by markscheel** [comment]
Yes, #738 addressed the issue.
