### ISSUE TITLE
Travis OSX builds are broken

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#810]
The Travis OSX builds are all failing (technically timing out as they try to compile gcc from source).  This appears to be a problem related to homebrew, which has changed from trying to download `https://homebrew.bintray.com/bottles/...` to just `/bottles/...`.  This, understandably, causes an error from curl, so homebrew decides to just compile everything from source, which takes too long.

**Comment by fmahebert** [comment]
A datapoint: on my laptop, Homebrew bottles are downloading as expected. Could this be Travis-related?

**Comment by fmahebert** [comment]
Here's a recent Homebrew change that is at least related, if not necessarily responsible: `https://github.com/Homebrew/brew/pull/4389`. This change was merged 11 days ago, so should not be solely responsible for builds breaking today.

**Comment by fmahebert** [comment]
I think I have a fix; I'm still exploring a few things but then I'll put in a PR.

**Comment by fmahebert** [comment]
Currently our Travis macOS setup does not update Homebrew before installing dependencies, and instead relies on Homebrew's auto-update-before-installing behavior.

In this case, the Homebrew auto-update brings in the commit I pasted in my earlier comment, which changes how bottle paths are specified. My suspicion is that by auto-updating Homebrew in the same invocation as the installation of a package, something is being cached/not evaluated/similar, leading to the broken bottle paths. I do not fully understand the problem, because I don't know why it manifested in our builds today in particular.

In any case, adding an explicit `brew update` command to the Travis script fixes the problem: the bottle path variable that was incorrect after the auto-update is correctly initialized when `brew install` is a new command.
