### ISSUE TITLE
Add a FaceNormal base tag

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#848]
# Feature request:

Instead of retrieving `Tags::Normalized<Tags::UnnormalizedFaceNormal<Dim>>` from the databox it would be useful to add a base tag so that we can retrieve `Tags::FaceNormal`.

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

**Comment by wthrowe** [comment]
This would require us to hardcode special behavior in `Tags::Normalized` so that it does something special when passed `Tags::UnnormalizedFaceNormal<...>`.  The savings here do not seem significant enough to warrant that sort of special casing.  (Note that a more realistic name for the base tag would be `Tags::NormalizedFaceNormal<Dim>`, so you'd only be saving about 20 characters out of 50 or so.)

In any code where you need to access the tag you can already write `using face_normal = Tags::Normalized<Tags::UnnormalizedFaceNormal<Dim>>;` to get a short name.

As the solution here is ugly, there is an easy workaround, and even in the absence of the workaround this change would not improve things very much, I'm closing this.
