### ISSUE TITLE
Add Doxygen group for analytic solutions

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#858]
As suggested by @gsb76 in #843 

### Component:

- [x] Documentation

**Comment by nilsdeppe** [comment]
I don't see why we want this. If I want to see what analytic solutions are available I want to see it for a specific system, not for all systems we have. @gsb76 can you explain the reason behind why you think we should have this?

**Comment by nilsvu** [comment]
As I understood it we have solutions that are applicable to other systems, which is why we keep them in `PointwiseFunctions` in the first place. Else we could put keep them with their corresponding system. Having a list of available solutions could be handy in that case.

**Comment by nilsdeppe** [comment]
Yes, but say we have 100 analytic solutions, it wouldn't help me to have a list of all of them. If I'm doing generalized harmonic + MHD, I would look in both Einstein Solutions and GRMHD solutions.

The reason for having them in `PointwiseFunctions` as opposed to `Evolution/Systems/...` is because the analytic solutions can be used in initial data. For example, in scalar field collapse the scalar field data is chosen analytically, and then the metric is solved for numerically. I would feel weird using something in `Evolution` for a non-evolution problem.

**Comment by nilsvu** [comment]
Based on your comment I fixed this to only list the namespaces with analytic solutions:
![bildschirmfoto 2018-08-21 um 10 54 09](https://user-images.githubusercontent.com/746230/44391601-93b62080-a530-11e8-9fc6-f7ece40b76be.png)

**Comment by nilsdeppe** [comment]
That looks useful to me :)
